// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface CoLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Energy.CoLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 level = 1;</code>
   * @return The level.
   */
  int getLevel();
}
