// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface HvacRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Energy.HvacRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   * @return The temp.
   */
  int getTemp();
}
