// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface SwitchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Energy.SwitchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool power = 1;</code>
   * @return The power.
   */
  boolean getPower();
}
