// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locationService.proto

package grpc.services.location;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:location.Empty)
    com.google.protobuf.MessageOrBuilder {
}
