// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locationService.proto

package grpc.services.location;

public interface IntensityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:location.IntensityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intensity = 1;</code>
   * @return The intensity.
   */
  int getIntensity();
}
