// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locationService.proto

package grpc.services.location;

public interface locationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:location.locationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool switch = 1;</code>
   * @return The switch.
   */
  boolean getSwitch();
}
