// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locationService.proto

package grpc.services.location;

public interface locationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:location.locationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string locationId = 1;</code>
   * @return The locationId.
   */
  java.lang.String getlocationId();
  /**
   * <code>string locationId = 1;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getlocationIdBytes();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 intensity = 3;</code>
   * @return The intensity.
   */
  int getIntensity();
}
