// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyService.proto

package grpc.services.energy;

public interface SwitchRequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:Energy.SwitchRequest)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>bool power = 1;</code>
	 */
	boolean getPower();
}
