// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingService.proto

package grpc.services.building;

public interface BuildingRequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:Building.DevicesRequest)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>bool devices = 1;</code>
	 */
	boolean getDevices();
}
