// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BuildingService.proto

package grpc.services.building;

public interface PrinterResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:Building.PrinterResponse)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string pList = 1;</code>
	 */
	java.lang.String getPList();

	/**
	 * <code>string pList = 1;</code>
	 */
	com.google.protobuf.ByteString getPListBytes();
}
